VERIFY_TOKEN = "1234"
server.port=10000
server.address=0.0.0.0
# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/whatsapp_responses
spring.datasource.username=postgres
spring.datasource.password=godisgr8

# DRIVER (optional but safer)
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect